---
title: "Evolución de las comunidades"
author: "Angel"
date: "29/4/2020"
output: html_document
---
Cargar paquetes.
```{r}
  library(tidyr)
  library(bibliometrix)
  library(tibble)
  library(igraph)
  library(ggplot2)
```

Cargar consulta de WoS.
```{r}
df_wos <- convert2df(file = "data/savedrecs (78).txt",
                     dbsource = "isi",
                     format = "plaintext")

df_wos$ID_WOS <- row.names(df_wos)

df_wos$ID_WOS <- ifelse(!is.na(df_wos$VL),
                        paste(df_wos$ID_WOS,
                              df_wos$VL,
                              sep = ", V"),
                        df_wos$ID_WOS)

df_wos$ID_WOS <- ifelse(!is.na(df_wos$BP),
                        paste(df_wos$ID_WOS,
                              df_wos$BP,
                              sep = ", P"),
                        df_wos$ID_WOS)

df_wos$ID_WOS <- ifelse(!is.na(df_wos$DI),
                        paste(df_wos$ID_WOS,
                              sep = ", DOI "),
                        df_wos$ID_WOS)

# Red de citaciones. 
network_citation <- 
  as_tibble(df_wos) %>% 
  select(ID_WOS, CR, PY) %>% 
  na.omit() %>% 
  separate_rows(CR, sep = ";") %>% 
  arrange(PY)
names(network_citation) <- c("source", "target", "year")
```

Cargar funciones componente gigante y production_sub_area.
```{r}
big_graph <- function(grafo){
  graph_x <- simplify(grafo)
  graph_x <- delete.vertices(graph_x,
                             which(degree(graph_x, mode = "in") == 1 &
                                   degree(graph_x, mode = "out") == 0))
  cl <- clusters(graph_x)
  graph_x <- induced.subgraph(graph_x,
                              which(cl$membership == which.max(cl$csize)))
}

source('production_sub_areas.R')
```

Evolución de las comunidades (y su producción) por año.
```{r}
minimo <- min(unique(network_citation$year))
maximo <- max(unique(network_citation$year))

evol_production_comunities <- tibble()

evol_num_comunities <- tibble(Year = c(minimo:maximo))
evol_num_cl = c()


for (i in minimo:maximo){
  graph <-
    network_citation %>% 
    filter(year <= i) %>% 
    select(source, target) %>% 
    graph.data.frame(directed = TRUE)
  
  graph <- big_graph(graph)
  prod_comunities <- production_sub_area(graph)
  
  evol_num_cl <- append(evol_num_cl,
                        length(prod_comunities$length_comunities$sub_area))
  
  ploting_evol_comunities <-
    ggplot(prod_comunities$production, aes(x=Year, y=frecuencia, color=sub_areas)) +
      geom_point(size=0.6) +
      geom_line() +
      labs(title = paste("Producción sub_area", as.character(i), sep = ""),
           x = "Years",
           y = "Frecuencia")
  print(ploting_evol_comunities)

  names(prod_comunities) <- c(paste("Level_", as.character(i), "_production", sep = ""),
                           paste("Level_", as.character(i), "_graph", sep = ""),
                           paste("Level_", as.character(i), "_length", sep = ""))
  
  evol_production_comunities <- append(evol_production_comunities,
                                       prod_comunities)
}

evol_num_comunities$Sub_areas <- evol_num_cl
plot_num_comunities <- 
  ggplot(evol_num_comunities, aes(x=Year, y=Sub_areas))+
  geom_point()+
  geom_line()+
  labs(title = "Evolución del número de comunidades",
       x = "Years")
print(plot_num_comunities)

```


