---
title: "Cluster"
output: html_document
---
```{r}
  library(igraph)
  library(tidyverse)
  library(tidyr)
  library(bibliometrix)
  library(ggplot2)
```

Importando grafo.
```{r}
graph <- read_graph("data/graph_tos_scopus (1).graphml", format = "graphml")
```

Cargando subarea (comunidades) a grafo.
```{r}
sub_areas <- cluster_louvain(as.undirected(graph), weights = NULL)
graph_1 <- 
  graph %>%
  set_vertex_attr(name = "sub_area",
                  value = membership(sub_areas))
```

Recolectando datos (fecha y longitud de comunidades).
```{r}
df_graph <- 
  data.frame(vertices = V(graph_1)$name, 
             sub_area = V(graph_1)$sub_area,
             stringsAsFactors = TRUE) %>% 
  arrange(desc(sub_area))
df_graph$year <- str_extract(df_graph$vertices, "[0-9]+")
df_graph <- na.omit(df_graph)

sizes_sub_areas <- 
  data.frame(sizes(sub_areas)) %>% 
  arrange(desc(Freq))
```

Producción por años.
```{r}
all_data <- 
  data.frame(Year = c(min(df_graph$year):max(df_graph$year)),
             stringsAsFactors = FALSE)
names_all_data <- list("Year")

for (i in 1:length(unique(df_graph$sub_area))){
  frecuency_sub_area <-
    df_graph %>% 
    filter(sub_area == i) %>% 
    count(year)
  names(frecuency_sub_area) <- c("Año", "Frecuencia")
  frecuency_sub_area$comunidades <- paste("sub_area", as.character(i), sep = "")
  
  frec_sub_area <- ifelse(all_data$Year %in% frecuency_sub_area$Año,
                          frecuency_sub_area$Frecuencia, 0)
  all_data <- cbind(all_data, frec_sub_area)
  
  names_all_data <- append(names_all_data,
                           paste("production_sub_area", as.character(i), sep = ""))
}
names(all_data) <- names_all_data
```

Graficas de los clusters principales.
```{r}
para_graficar <- all_data %>% 
  select(Year, production_sub_area12, production_sub_area10,
         production_sub_area9, production_sub_area4) %>% 
  gather(key="sub_areas", value="frecuencia", 2:5)

ggplot(para_graficar, aes(x=Year, y=frecuencia, color=sub_areas)) +
  xlim(c(1940, 2020)) +
  geom_point(size=0.6) +
  geom_line() +
  labs(title = "Producción sub_areas",
       x = "Years",
       y = "Frecuencia")
```

